from neopixel import *

# LED strip configuration:
LED_COUNT      = 150      # Number of LED pixels.
LED_PIN        = 18      # GPIO pin connected to the pixels (must support PWM!).
LED_FREQ_HZ    = 800000  # LED signal frequency in hertz (usually 800khz)
LED_DMA        = 5       # DMA channel to use for generating signal (try 5)
LED_BRIGHTNESS = 255     # Set to 0 for darkest and 255 for brightest
LED_INVERT     = False   # True to invert the signal (when using NPN transistor level shift)


def bullshit(strip, pos, color, char):
  if char == "A":
    A(strip, pos, color)
  elif char == "B":
      B(strip, pos, color)
  elif char == "C":
      C(strip, pos, color)
  elif char == "D":
      D(strip, pos, color)
  elif char == "E":
      E(strip, pos, color)
  elif char == "F":
      F(strip, pos, color)
  elif char == "G":
      G(strip, pos, color)
  elif char == "H":
      H(strip, pos, color)
  elif char == "I":
      I(strip, pos, color)
  elif char == "J":
      J(strip, pos, color)
  elif char == "K":
      K(strip, pos, color)
  elif char == "L":
      L(strip, pos, color)
  elif char == "M":
      M(strip, pos, color)
  elif char == "N":
      N(strip, pos, color)
  elif char == "O":
      O(strip, pos, color)
  elif char == "P":
      P(strip, pos, color)
  elif char == "Q":
      Q(strip, pos, color)
  elif char == "R":
      R(strip, pos, color)
  elif char == "S":
      S(strip, pos, color)
  elif char == "T":
      T(strip, pos, color)
  elif char == "U":
      U(strip, pos, color)
  elif char == "V":
      V(strip, pos, color)
  elif char == "W":
      W(strip, pos, color)
  elif char == "X":
      X(strip, pos, color)
  elif char == "Y":
      Y(strip, pos, color)
  elif char == "Z":
      Z(strip, pos, color)

def display(strip, string):
  string = string.upper()
  for i in range(0, len(string)):
    bullshit(strip, i, Color(0, 0, 255), string[i])

def A(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def B(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 13, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 21, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 37, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 45, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 53, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.show()

def C(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.show()

def D(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 13, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 53, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.show()

def E(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def F(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.show()

def G(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.show()

def H(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def I(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 11, color)
  strip.setPixelColor(64 * pos + 19, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def J(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 11, color)
  strip.setPixelColor(64 * pos + 19, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 50, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.show()

def K(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 12, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 19, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 44, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 63, color)
  strip.show()

def L(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def M(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 11, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 19, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def N(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 10, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 18, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 44, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 52, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def O(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.show()

def P(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.show()

def Q(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 49, color)
  strip.setPixelColor(64 * pos + 50, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 52, color)
  strip.setPixelColor(64 * pos + 53, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def R(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 37, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 45, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

def S(strip, pos, color):
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 25, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 29, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.show()

def T(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 11, color)
  strip.setPixelColor(64 * pos + 19, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.show()

def U(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.show()

def V(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 41, color)
  strip.setPixelColor(64 * pos + 45, color)
  strip.setPixelColor(64 * pos + 50, color)
  strip.setPixelColor(64 * pos + 52, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.show()

def W(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 11, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 16, color)
  strip.setPixelColor(64 * pos + 19, color)
  strip.setPixelColor(64 * pos + 22, color)
  strip.setPixelColor(64 * pos + 24, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 30, color)
  strip.setPixelColor(64 * pos + 32, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 38, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.show()

def X(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 17, color)
  strip.setPixelColor(64 * pos + 21, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 33, color)
  strip.setPixelColor(64 * pos + 37, color)
  strip.setPixelColor(64 * pos + 40, color)
  strip.setPixelColor(64 * pos + 46, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 54, color)
  strip.show()

def Y(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 8, color)
  strip.setPixelColor(64 * pos + 14, color)
  strip.setPixelColor(64 * pos + 17, color)
  strip.setPixelColor(64 * pos + 21, color)
  strip.setPixelColor(64 * pos + 26, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 28, color)
  strip.setPixelColor(64 * pos + 35, color)
  strip.setPixelColor(64 * pos + 43, color)
  strip.setPixelColor(64 * pos + 51, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.show()

def Z(strip, pos, color):
  strip.setPixelColor(64 * pos + 0, color)
  strip.setPixelColor(64 * pos + 1, color)
  strip.setPixelColor(64 * pos + 2, color)
  strip.setPixelColor(64 * pos + 3, color)
  strip.setPixelColor(64 * pos + 4, color)
  strip.setPixelColor(64 * pos + 5, color)
  strip.setPixelColor(64 * pos + 6, color)
  strip.setPixelColor(64 * pos + 13, color)
  strip.setPixelColor(64 * pos + 20, color)
  strip.setPixelColor(64 * pos + 27, color)
  strip.setPixelColor(64 * pos + 34, color)
  strip.setPixelColor(64 * pos + 41, color)
  strip.setPixelColor(64 * pos + 48, color)
  strip.setPixelColor(64 * pos + 56, color)
  strip.setPixelColor(64 * pos + 57, color)
  strip.setPixelColor(64 * pos + 58, color)
  strip.setPixelColor(64 * pos + 59, color)
  strip.setPixelColor(64 * pos + 60, color)
  strip.setPixelColor(64 * pos + 61, color)
  strip.setPixelColor(64 * pos + 62, color)
  strip.show()

# Define functions which animate LEDs in various ways.
def colorWipe(strip, color, wait_ms=50):
  for i in range(strip.numPixels()):
    strip.setPixelColor(i, color)
  strip.show()


def main():
    # Create NeoPixel object with appropriate configuration.
  strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS)
    # Intialize the library (must be called once before other functions).
  strip.begin()
  string = ""
  while True:
    string = raw_input("Enter the string: ")
    print(string)
    colorWipe(strip, Color(0, 0, 0))
    display(strip, string)


main()
