class Letter(object):
  def __init__(self, strip, pos):
    self.strip = strip
    self.pos = pos  

  @staticmethod
  def A(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def B(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 13, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 21, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 37, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 45, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 53, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.show()
  @staticmethod
  def C(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.show()
  @staticmethod
  def D(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 13, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 53, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.show()
  @staticmethod
  def E(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def F(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.show()
  @staticmethod
  def G(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.show()
  @staticmethod
  def H(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def I(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 11, color)
    strip.setPixelColor(64 * pos + 19, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def J(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 11, color)
    strip.setPixelColor(64 * pos + 19, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 50, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.show()
  @staticmethod
  def K(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 12, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 19, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 44, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 63, color)
    strip.show()
  @staticmethod
  def L(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def M(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 11, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 19, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def N(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 10, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 18, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 44, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 52, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def O(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.show()
  @staticmethod
  def P(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.show()
  @staticmethod
  def Q(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 49, color)
    strip.setPixelColor(64 * pos + 50, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 52, color)
    strip.setPixelColor(64 * pos + 53, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def R(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 37, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 45, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
  @staticmethod
  def S(strip, pos, color):
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 25, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 29, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.show()
  @staticmethod
  def T(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 11, color)
    strip.setPixelColor(64 * pos + 19, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.show()
  @staticmethod
  def U(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.show()
  @staticmethod
  def V(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 41, color)
    strip.setPixelColor(64 * pos + 45, color)
    strip.setPixelColor(64 * pos + 50, color)
    strip.setPixelColor(64 * pos + 52, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.show()
  @staticmethod
  def W(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 11, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 16, color)
    strip.setPixelColor(64 * pos + 19, color)
    strip.setPixelColor(64 * pos + 22, color)
    strip.setPixelColor(64 * pos + 24, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 30, color)
    strip.setPixelColor(64 * pos + 32, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 38, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.show()
  @staticmethod
  def X(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 17, color)
    strip.setPixelColor(64 * pos + 21, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 33, color)
    strip.setPixelColor(64 * pos + 37, color)
    strip.setPixelColor(64 * pos + 40, color)
    strip.setPixelColor(64 * pos + 46, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 54, color)
    strip.show()
  @staticmethod
  def Y(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 8, color)
    strip.setPixelColor(64 * pos + 14, color)
    strip.setPixelColor(64 * pos + 17, color)
    strip.setPixelColor(64 * pos + 21, color)
    strip.setPixelColor(64 * pos + 26, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 28, color)
    strip.setPixelColor(64 * pos + 35, color)
    strip.setPixelColor(64 * pos + 43, color)
    strip.setPixelColor(64 * pos + 51, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.show()
  @staticmethod
  def Z(strip, pos, color):
    strip.setPixelColor(64 * pos + 0, color)
    strip.setPixelColor(64 * pos + 1, color)
    strip.setPixelColor(64 * pos + 2, color)
    strip.setPixelColor(64 * pos + 3, color)
    strip.setPixelColor(64 * pos + 4, color)
    strip.setPixelColor(64 * pos + 5, color)
    strip.setPixelColor(64 * pos + 6, color)
    strip.setPixelColor(64 * pos + 13, color)
    strip.setPixelColor(64 * pos + 20, color)
    strip.setPixelColor(64 * pos + 27, color)
    strip.setPixelColor(64 * pos + 34, color)
    strip.setPixelColor(64 * pos + 41, color)
    strip.setPixelColor(64 * pos + 48, color)
    strip.setPixelColor(64 * pos + 56, color)
    strip.setPixelColor(64 * pos + 57, color)
    strip.setPixelColor(64 * pos + 58, color)
    strip.setPixelColor(64 * pos + 59, color)
    strip.setPixelColor(64 * pos + 60, color)
    strip.setPixelColor(64 * pos + 61, color)
    strip.setPixelColor(64 * pos + 62, color)
    strip.show()
